version: "3.4"
services:
  app:
    build:
      context: .
    working_dir: /web/html/
    volumes:
      - $PWD/src/:/web/html/
      - $PWD/resources/certs:/etc/nginx/certs
      - $PWD/resources/secrets:/run/secrets
    env_file: $PWD/src/.env
    container_name: personal-site-app
    ports:
      - 80:80
      - 443:443
  database:
    image: mariadb:10.4
    volumes:
      - personal-site-db:/var/lib/mysql
    env_file: $PWD/src/.env
    ports:
      - 3306:3306
    container_name: personal-site-db
volumes:
  personal-site-db:
    name: personal-site-db
