version: '2'
services:
  app:
    image: th0rn0/personal-site:latest@sha256:ee32c3825f1b3363b3297e42e47459a62a380b360c61a3e82b1958f0cbf23eb3
    environment:
      APP_DEBUG: 'false'
      APP_ENV: production
      APP_URL: th0rn0.co.uk
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_DATABASE: personal_site
      DB_HOST: database
      DB_MIGRATE: 'true'
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: '3306'
      DB_USERNAME: ${DB_USERNAME}
      ENABLE_HTTPS: 'false'
    volumes:
    - lan_manager_storage:/web/html/storage/
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always
    links:
      - database:database
  database:
    image: linuxserver/mariadb:110.4.12mariabionic-ls52
    environment:
      MYSQL_DATABASE: personal_site
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: ${DB_USERNAME}
    volumes:
    - perosnal_site_storage:/var/lib/mysql
    ports:
    - 3306:3306/tcp
  loadbalancer:
    image: traefik:v2.0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /certs:/certs:z
    - /acme:/acme:z
    ports:
    - 80:80/tcp
    - 443:443/tcp
    - 8080:8080/tcp
    command:
    - --api.insecure=true
    - --providers.rancher=true
    - --entryPoints.web.address=:80
    - --entryPoints.websecure.address=:443
    - --providers.rancher.exposedByDefault=false
    - --certificatesresolvers.le.acme.email=th0rn0@lanops.co.uk
    - --certificatesresolvers.le.acme.storage=/acme/acme.json
    - --certificatesresolvers.le.acme.tlschallenge=true
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.scheduler.affinity:host_label: loadbalancer=true
      io.rancher.container.create_agent: 'true'
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'